// Nightfall Globe: guess where a city is on the Earth at night.
// Imagery lists come from tiles/manifest.js (or are inlined by tools/build_single.py).
const NIGHT_TEXTURE = TILES.base;
const HI_TILES = TILES.hi;
const Z7 = TILES.z7;
const Z8 = TILES.z8 || [];

// ---------- Cities ----------
// CITIES ([name, country, lat, lon, note, population]) comes from cities.js, generated by tools/build_cities.py

// ---------- Utils ----------
const R = 1;
const DEG = Math.PI/180;
function latLonToVec3(lat, lon, r=R){
  const phi = (lon+180)*DEG, theta = (90-lat)*DEG;
  return new THREE.Vector3(-r*Math.cos(phi)*Math.sin(theta), r*Math.cos(theta), r*Math.sin(phi)*Math.sin(theta));
}
function vec3ToLatLon(v){
  const n = v.clone().normalize();
  const theta = Math.acos(Math.max(-1,Math.min(1,n.y)));
  const phi = Math.atan2(n.z, -n.x);
  let lon = phi/DEG - 180; if(lon < -180) lon += 360;
  return {lat: 90 - theta/DEG, lon};
}
function haversine(a, b){
  const dLat=(b.lat-a.lat)*DEG, dLon=(b.lon-a.lon)*DEG;
  const s=Math.sin(dLat/2)**2+Math.cos(a.lat*DEG)*Math.cos(b.lat*DEG)*Math.sin(dLon/2)**2;
  return 6371*2*Math.atan2(Math.sqrt(s),Math.sqrt(1-s));
}
function pointsFor(km){ return Math.round(1000*Math.exp(-km/1500)); }
function mulberry32(a){return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function seedFromDate(d){ return d.getFullYear()*10000 + (d.getMonth()+1)*100 + d.getDate(); }
// Five distinct cities, each drawn with probability proportional to population^(2/3): big cities come up
// often, but the long tail of 100k towns still gets a turn.
const CITY_WEIGHT = CITIES.map(c=>Math.pow(c[5]||15000, 2/3));
function pickFive(seed){
  const rnd = mulberry32(seed*2654435761 % 2**31);
  const w = CITY_WEIGHT.slice(); let total = w.reduce((s,x)=>s+x, 0);
  const picks = [];
  while(picks.length<5){
    let r = rnd()*total, i = 0;
    while(i < w.length-1 && r >= w[i]){ r -= w[i]; i++; }
    picks.push(CITIES[i]); total -= w[i]; w[i] = 0;
  }
  return picks;
}
const fmtKm = km => km<10 ? km.toFixed(1) : Math.round(km).toLocaleString();
const dateKey = d => d.toISOString().slice(0,10);
const store = {
  get(k){ try{ return JSON.parse(localStorage.getItem(k)); }catch(e){ return null; } },
  set(k,v){ try{ localStorage.setItem(k, JSON.stringify(v)); }catch(e){} }
};

// ---------- Scene ----------
// Model: the camera is fixed on the +Z axis looking at the origin; all rotation happens on the `earth` group.
const canvas = document.getElementById('stage');
const renderer = new THREE.WebGLRenderer({canvas, antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(40, 1, 0.01, 100);
let camDist = 3.1;
const MIN_D=1.07; let MAX_D=4.5, FIT_D=3.1;

const stars = (()=>{
  const n=2500, pos=new Float32Array(n*3);
  for(let i=0;i<n;i++){ const u=Math.random()*2-1, a=Math.random()*Math.PI*2, s=Math.sqrt(1-u*u); const v=new THREE.Vector3(s*Math.cos(a),u,s*Math.sin(a)).multiplyScalar(40); pos.set([v.x,v.y,v.z],i*3); }
  const g=new THREE.BufferGeometry(); g.setAttribute('position',new THREE.BufferAttribute(pos,3));
  return new THREE.Points(g,new THREE.PointsMaterial({color:0x8A8FA8,size:0.09,sizeAttenuation:true,transparent:true,opacity:.8}));
})();
scene.add(stars);

const earth = new THREE.Group(); scene.add(earth);
const tex = new THREE.TextureLoader().load(NIGHT_TEXTURE, ()=>{ document.getElementById('modeline').textContent = modeLabel(); });
tex.anisotropy = renderer.capabilities.getMaxAnisotropy();
const globe = new THREE.Mesh(new THREE.SphereGeometry(R, 96, 64), new THREE.MeshBasicMaterial({map:tex}));
earth.add(globe);

// Detail layers. Everything ships inside the page, but GPU memory on phones is finite, so each layer keeps only the
// tiles near the current view resident and disposes the rest as you move. All layers sit at the globe's own radius and
// paint over each other in order without depth testing: stacking them at growing radii looked the same but put the
// picture you see up to 0.35% above the sphere the tap ray is tested against, which at full zoom moved taps near the
// screen edges by tens of pixels. 32 tiles of 2048px (16k equirect, ≈2.4 km/px),
// then 512px patches at ≈1.2 km/px over every lit region, then 2.25° tiles at ≈490 m/px (NASA GIBS
// VIIRS_CityLights_2012, its finest level) over the same regions, used only when zoomed right in.
const texLoader = new THREE.TextureLoader();
function makeLayer(group, items, order, segs, opts){
  const L={group, order, segs, ...opts, items: items.map(it=>{
    const c=latLonToVec3((it.lat0+it.lat1)/2,(it.lon0+it.lon1)/2).normalize();
    const corner=latLonToVec3(it.lat0,it.lon0).normalize();
    return {...it, c, half: Math.max(c.angleTo(corner), c.angleTo(latLonToVec3(it.lat1,it.lon0).normalize())), mesh:null, loading:false};
  }), busy:0};
  return L;
}
function loadItem(L, it){
  it.loading=true; L.busy++;
  texLoader.load(it.src, tx=>{
    tx.anisotropy=renderer.capabilities.getMaxAnisotropy(); tx.minFilter=THREE.LinearMipmapLinearFilter;
    const geo=new THREE.SphereGeometry(R, L.segs, L.segs, (it.lon0+180)*DEG, (it.lon1-it.lon0)*DEG, (90-it.lat1)*DEG, (it.lat1-it.lat0)*DEG);
    it.mesh=new THREE.Mesh(geo, new THREE.MeshBasicMaterial({map:tx, depthTest:false, depthWrite:false})); it.mesh.renderOrder=L.order; L.group.add(it.mesh);
    it.loading=false; L.busy--;
  }, undefined, ()=>{ it.loading=false; L.busy--; });
}
function unloadItem(L, it){
  L.group.remove(it.mesh); it.mesh.geometry.dispose(); it.mesh.material.map.dispose(); it.mesh.material.dispose(); it.mesh=null;
}
function viewCentreDir(){ return new THREE.Vector3(0,0,1).applyQuaternion(earth.quaternion.clone().invert()); }
function updateLayer(L){
  if(camDist>L.maxDist) { // layer not needed at this zoom: drop everything
    L.items.forEach(it=>{ if(it.mesh) unloadItem(L,it); }); return;
  }
  // angular radius of the area worth loading: the horizon, or when zoomed in, the screen's diagonal (with slack for
  // the view offset and the surface curving away at the edges)
  const vc=viewCentreDir();
  const halfDiag=(camDist-1)*Math.tan(camera.fov/2*DEG)*Math.sqrt(1+camera.aspect*camera.aspect);
  const vis=Math.min(Math.acos(1/camDist), Math.asin(Math.min(1,halfDiag))*1.6);
  let resident=0; const wanted=[];
  for(const it of L.items){
    const a=it.c.angleTo(vc);
    if(it.mesh){ resident++; if(a>vis+it.half+L.unloadPad) { unloadItem(L,it); resident--; } }
    else if(!it.loading && a<vis+it.half+L.loadPad) wanted.push([a,it]);
  }
  wanted.sort((x,y)=>x[0]-y[0]);
  for(const [a,it] of wanted){ if(L.busy>=2 || resident+L.busy>=L.cap) break; loadItem(L,it); }
}
const hiShell=new THREE.Group(); earth.add(hiShell);
const detail=new THREE.Group(); earth.add(detail);
const fine=new THREE.Group(); earth.add(fine);
const layers=[];
if(renderer.capabilities.maxTextureSize>=2048 && HI_TILES.length===32){
  const items=[]; for(let j=0;j<4;j++) for(let i=0;i<8;i++) items.push({lon0:-180+i*45, lon1:-135+i*45, lat0:90-(j+1)*45, lat1:90-j*45, src:HI_TILES[j*8+i]});
  layers.push(makeLayer(hiShell, items, 1, 24, {maxDist:99, loadPad:0.15, unloadPad:0.6, cap:16}));
  layers.push(makeLayer(detail, Z7.map(z=>({lon0:z[0],lon1:z[1],lat0:z[2],lat1:z[3],src:z[4]})), 2, 10, {maxDist:2.6, loadPad:0.08, unloadPad:0.35, cap:70}));
  layers.push(makeLayer(fine, Z8.map(z=>({lon0:z[0],lon1:z[1],lat0:z[2],lat1:z[3],src:z[4]})), 3, 6, {maxDist:1.35, loadPad:0.03, unloadPad:0.18, cap:48}));
}
let lastLayerT=0;
function tickLayers(now){ if(now-lastLayerT<250) return; lastLayerT=now; layers.forEach(updateLayer); }

// atmosphere rim glow (symmetric, so it can stay outside the rotating group)
const atmo = new THREE.Mesh(new THREE.SphereGeometry(R*1.035, 64, 48), new THREE.ShaderMaterial({
  transparent:true, side:THREE.BackSide, depthWrite:false, blending:THREE.AdditiveBlending,
  uniforms:{},
  vertexShader:`varying vec3 vN; varying vec3 vP; void main(){ vN=normalize(normalMatrix*normal); vec4 mv=modelViewMatrix*vec4(position,1.0); vP=mv.xyz; gl_Position=projectionMatrix*mv; }`,
  fragmentShader:`varying vec3 vN; varying vec3 vP; void main(){ float f=pow(max(0.0, dot(normalize(vN), normalize(-vP))), 4.0); gl_FragColor=vec4(0.32,0.45,0.85,1.0)*f*0.9; }`
}));
scene.add(atmo);

const markers = new THREE.Group(); earth.add(markers);
// A dot and a pulsing ring lying flat on the surface, centred on the point. (An upright pin with a raised head
// leans away from its base in perspective, so the head never sat where you tapped.)
function makePin(color, r=0.014){
  const g=new THREE.Group();
  const dot=new THREE.Mesh(new THREE.CircleGeometry(r,32), new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide}));
  const ring=new THREE.Mesh(new THREE.RingGeometry(r*1.6,r*2.1,40), new THREE.MeshBasicMaterial({color,transparent:true,opacity:.55,side:THREE.DoubleSide}));
  dot.rotation.x=-Math.PI/2; ring.rotation.x=-Math.PI/2; dot.renderOrder=ring.renderOrder=10; // after the imagery shells
  g.add(dot,ring); return g;
}
function placePin(pin, lat, lon){
  const p=latLonToVec3(lat,lon,R*1.0006); // just clear of the base mesh's facets, which dip below R between vertices
  pin.position.copy(p);
  pin.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0), p.clone().normalize());
}
function arcBetween(a, b, color){
  const va=latLonToVec3(a.lat,a.lon), vb=latLonToVec3(b.lat,b.lon);
  const ang=va.angleTo(vb); const pts=[]; const N=64;
  const q0=new THREE.Quaternion(), q1=new THREE.Quaternion().setFromUnitVectors(va.clone().normalize(), vb.clone().normalize());
  for(let i=0;i<=N;i++){
    const t=i/N; const q=q0.clone().slerp(q1,t);
    pts.push(va.clone().applyQuaternion(q).normalize().multiplyScalar(R*(1+0.02+Math.sin(t*Math.PI)*ang*0.12)));
  }
  return new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts), new THREE.LineBasicMaterial({color,transparent:true,opacity:.9}));
}

// ---------- Camera / orientation ----------
const Y_AXIS=new THREE.Vector3(0,1,0), X_AXIS=new THREE.Vector3(1,0,0), Z_AXIS=new THREE.Vector3(0,0,1);
function updateCamera(){ camDist=Math.max(MIN_D,Math.min(MAX_D,camDist)); camera.position.set(0,0,camDist); camera.lookAt(0,0,0); }
// Keep north pointing up on screen: undo any roll around the view axis
function levelNorth(strength=1){
  const n=Y_AXIS.clone().applyQuaternion(earth.quaternion);
  // never let the globe flip over a pole: if north would point below the screen's horizontal, pitch back
  if(n.y<0){ earth.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(X_AXIS, Math.atan2(n.y,n.z))); n.copy(Y_AXIS).applyQuaternion(earth.quaternion); }
  const m=Math.hypot(n.x,n.y); if(m<0.05) return; // looking straight at a pole: "north up" is meaningless, leave it
  const w=Math.min(1,strength*Math.min(1,m/0.3)); // ease off near the poles so the correction can't yank
  earth.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(Z_AXIS, Math.atan2(n.x,n.y)*w));
}
// Orientation that puts (lat,lon) at the screen centre with north up
function quatFacing(lat, lon){
  const f=latLonToVec3(lat,lon).normalize();
  let up=Y_AXIS.clone(); if(Math.abs(f.dot(up))>0.999) up=new THREE.Vector3(0,0,1);
  const u=up.clone().sub(f.clone().multiplyScalar(up.dot(f))).normalize();
  const r=u.clone().cross(f).normalize();
  const m=new THREE.Matrix4().makeBasis(r,u,f); // maps x->r, y->u, z->f
  return new THREE.Quaternion().setFromRotationMatrix(m).invert();
}
function rotateBy(axis, angle){ earth.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(axis, angle)); }
function radPerPx(){ return 2*(camDist-1)*Math.tan(camera.fov/2*DEG)/canvas.clientHeight; }
// screen delta -> globe rotation (drag right moves the globe right, drag down moves it down)
function applyDrag(dx,dy){ const k=radPerPx(); rotateBy(Y_AXIS, dx*k); rotateBy(X_AXIS, dy*k); levelNorth(); }

// Frame the globe in the space left between the top bar and the prompt card, whatever the screen shape.
// Everything is measured from the canvas's own box so it stays right even when window.inner* disagrees with the layout.
function layout(){
  const cr=canvas.getBoundingClientRect(); const w=Math.max(1,Math.round(cr.width)), h=Math.max(1,Math.round(cr.height));
  const topEl=document.querySelector('.topbar'), promptEl=document.getElementById('prompt');
  const top=topEl.getBoundingClientRect().bottom-cr.top+6;
  const pr=promptEl.getBoundingClientRect();
  const promptShown=!promptEl.hidden && pr.height>0;
  const bottom=promptShown ? pr.top-cr.top-6 : h-6;
  const freeH=Math.max(120,bottom-top), centerY=(top+bottom)/2;
  camera.aspect=w/h;
  camera.setViewOffset(w,h,0,h/2-centerY,w,h); // shifts the image so the origin lands on centerY
  const targetPx=0.47*Math.min(w-16,freeH);
  const tt=targetPx/(h/2)*Math.tan(camera.fov/2*DEG);
  const wasFit=Math.abs(camDist-FIT_D)<1e-6 || camDist>=MAX_D-1e-6;
  FIT_D=Math.max(2.2, 1/Math.sin(Math.atan(tt)));
  MAX_D=FIT_D;
  if(wasFit || camDist>MAX_D) camDist=FIT_D;
  updateCamera();
}
function resize(){
  const cr=canvas.getBoundingClientRect(); const w=Math.max(1,Math.round(cr.width)), h=Math.max(1,Math.round(cr.height));
  renderer.setSize(w,h,false); layout();
}
addEventListener('resize',resize); resize();
if(window.ResizeObserver){ const ro=new ResizeObserver(()=>resize()); ro.observe(canvas); ro.observe(document.getElementById('prompt')); ro.observe(document.querySelector('.topbar')); }
addEventListener('orientationchange',()=>setTimeout(resize,300));
function recenter(){ // whole globe, centred, keeping the current heading
  tween=null; spin.rate=0; layout();
  const c=hitGlobe(canvas.clientWidth/2, canvas.clientHeight/2) || {lat:20,lon:0};
  flyTo(c.lat, c.lon, FIT_D);
}
earth.quaternion.copy(quatFacing(25,10));

// camera tween (orientation slerp + distance)
let tween=null;
function flyTo(lat, lon, dist){
  tween={t0:performance.now(),dur:900,q0:earth.quaternion.clone(),q1:quatFacing(lat,lon),d0:camDist,d1:Math.max(MIN_D,Math.min(MAX_D,dist))};
}

// ---------- Input ----------
const ray=new THREE.Raycaster();
function screenToNdc(x,y){ const r=canvas.getBoundingClientRect(); return new THREE.Vector2(((x-r.left)/r.width)*2-1, -((y-r.top)/r.height)*2+1); }
// Exact ray/sphere test against the true sphere, not the faceted mesh (whose facets dip below R between vertices)
function hitGlobe(x,y){
  ray.setFromCamera(screenToNdc(x,y),camera); const o=ray.ray.origin, d=ray.ray.direction; const tc=-o.dot(d);
  const q=o.clone().add(d.clone().multiplyScalar(tc)); const rho2=q.lengthSq(); if(tc<0 || rho2>R*R) return null;
  const p=q.sub(d.clone().multiplyScalar(Math.sqrt(R*R-rho2)));
  return vec3ToLatLon(p.applyQuaternion(earth.quaternion.clone().invert()));
}
// What the pointer is "holding" on the globe: a unit direction (world space) plus the geometry needed to keep a drag
// going off the globe. Inside 80% of the disc that is the surface point under the pointer. Grabbing the true surface
// out to the limb makes the turn rate blow up at the edge and stop dead beyond it, so past that radius the grab angle
// keeps growing at the rate it had at 80%: the same response continues smoothly over the horizon and off the globe.
// The angle is capped short of the far pole; beyond the cap dragTo adds the radial motion directly, so it never stalls.
const GRAB_RHO0=0.8, GRAB_SLOPE=1/Math.sqrt(1-GRAB_RHO0*GRAB_RHO0), GRAB_AMAX=2.6;
const GRAB_RHOCAP=GRAB_RHO0+(GRAB_AMAX-Math.asin(GRAB_RHO0))/GRAB_SLOPE; // radius where the cap starts
function grabAt(x,y){
  ray.setFromCamera(screenToNdc(x,y),camera);
  const o=ray.ray.origin, d=ray.ray.direction; const tc=-o.dot(d);
  const q=o.clone().add(d.clone().multiplyScalar(tc)); const rho=q.length()/R; // ray's closest approach to the centre
  const a = rho<=GRAB_RHO0 ? Math.asin(rho) : Math.min(GRAB_AMAX, Math.asin(GRAB_RHO0)+(rho-GRAB_RHO0)*GRAB_SLOPE);
  const qh=q.normalize(); // radial direction in the view plane (zero vector at the exact centre, which is harmless)
  const dirAt=a=>qh.clone().multiplyScalar(Math.sin(a)).sub(d.clone().multiplyScalar(Math.cos(a))).normalize();
  const n=d.clone().negate().cross(qh).normalize(); // axis that tilts the grab point further outward
  // dir: the eased grab direction used for dragging. hit: the exact surface point when the pointer is on the globe.
  return {dir:dirAt(a), hit: rho<=1 ? dirAt(Math.asin(rho)) : null, rho, n, capped: a>=GRAB_AMAX};
}
function surfaceDir(x,y){ return grabAt(x,y).dir; }
// Zoom by a factor while keeping the point under (x,y) fixed on screen, as a map does: note what the pointer is over,
// move the camera, then turn the globe so that point is back under the pointer. Levelling north afterwards adds a
// little roll about the screen centre, so anchor once more to take that back out.
function zoomAt(x,y,factor){
  const g0=grabAt(x,y); const held=(g0.hit||g0.dir).applyQuaternion(earth.quaternion.clone().invert()); // in globe coordinates
  camDist*=factor; updateCamera(); camera.updateMatrixWorld();
  const g1=grabAt(x,y); const target=g1.hit||g1.dir;
  const anchor=()=>earth.quaternion.premultiply(new THREE.Quaternion().setFromUnitVectors(held.clone().applyQuaternion(earth.quaternion), target));
  anchor(); levelNorth(); anchor();
}

const pointers=new Map(); let dragging=false, autoSpin=true;
let downPos=null, maxMove=0, grabDir=null, grab=null, lastPinch=0, lastCentroid=null;
let spin={axis:new THREE.Vector3(0,1,0), rate:0}, lastMoveT=0;
   // inertia: rate in rad/ms around a world axis

function dragTo(x,y,prev){
  const now=performance.now(), dt=Math.max(8,now-lastMoveT); lastMoveT=now;
  const g=grabAt(x,y), dir=g.dir;
  if(grabDir){
    let q=new THREE.Quaternion().setFromUnitVectors(grabDir,dir);
    if(g.capped && grab) q.premultiply(new THREE.Quaternion().setFromAxisAngle(g.n, GRAB_SLOPE*(g.rho-Math.max(grab.rho,GRAB_RHOCAP)))); // radial motion beyond the cap
    let ang=2*Math.acos(Math.min(1,Math.abs(q.w)));
    const MAXA=0.35; // cap one event at 20°: a very fast swipe can't produce a wild flip
    if(ang>MAXA){ q=new THREE.Quaternion().slerp(q, MAXA/ang); ang=MAXA; }
    earth.quaternion.premultiply(q); levelNorth();
    if(ang>1e-5){ const s=Math.sqrt(Math.max(1e-12,1-q.w*q.w)); const axis=new THREE.Vector3(q.x/s,q.y/s,q.z/s); const rate=Math.min(0.004, ang/dt);
      // smooth the fling estimate over recent events
      spin.axis.lerp(axis, 0.5).normalize(); spin.rate=spin.rate*0.5+rate*0.5; }
    else spin.rate*=0.5;
  } else { applyDrag(x-prev.x,y-prev.y); spin.rate=0; }
  grabDir=dir; grab=g;
}

canvas.addEventListener('pointerdown',e=>{
  if(e.button!==undefined && e.button!==0 && e.pointerType==='mouse') return;
  e.preventDefault();
  try{ canvas.setPointerCapture(e.pointerId); }catch(_){}
  pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
  tween=null; autoSpin=false; spin.rate=0; dragging=true; canvas.classList.add('dragging');
  if(pointers.size===1){ downPos={x:e.clientX,y:e.clientY}; maxMove=0; grab=grabAt(e.clientX,e.clientY); grabDir=grab.dir; lastMoveT=performance.now(); }
  else { grabDir=null; grab=null; maxMove=99; lastPinch=0; lastCentroid=null; }
});
canvas.addEventListener('pointermove',e=>{
  if(!pointers.has(e.pointerId)) return;
  const prev=pointers.get(e.pointerId); pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
  if(downPos) maxMove=Math.max(maxMove, Math.hypot(e.clientX-downPos.x,e.clientY-downPos.y));
  if(pointers.size===1){ dragTo(e.clientX,e.clientY,prev); }
  else if(pointers.size===2){
    const [a,b]=[...pointers.values()]; const d=Math.hypot(a.x-b.x,a.y-b.y); const c={x:(a.x+b.x)/2,y:(a.y+b.y)/2};
    if(lastPinch){ zoomAt(c.x,c.y,lastPinch/d); }
    if(lastCentroid){ applyDrag(c.x-lastCentroid.x,c.y-lastCentroid.y); }
    lastPinch=d; lastCentroid=c;
  }
});
function endPointer(e){
  if(!pointers.has(e.pointerId)) return;
  pointers.delete(e.pointerId); lastPinch=0; lastCentroid=null;
  if(pointers.size===1){ const rest=[...pointers.values()][0]; grab=grabAt(rest.x,rest.y); grabDir=grab.dir; maxMove=99; downPos=null; }
  if(pointers.size===0){
    dragging=false; canvas.classList.remove('dragging');
    if(downPos && maxMove<8 && e.type==='pointerup'){ spin.rate=0; tapAt(downPos.x,downPos.y); } // where the finger landed, not where it lifted
    else if(performance.now()-lastMoveT>80){ spin.rate=0; } // finger paused before lifting: no fling
    downPos=null; grabDir=null; grab=null;
  }
}
canvas.addEventListener('pointerup',endPointer); canvas.addEventListener('pointercancel',endPointer);
// iOS: stop the host page from scrolling/zooming while we drag on the canvas
['touchstart','touchmove','touchend'].forEach(t=>canvas.addEventListener(t,e=>{ if(e.cancelable) e.preventDefault(); },{passive:false}));
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('wheel',e=>{
  e.preventDefault(); autoSpin=false; tween=null;
  const d = e.deltaMode===1 ? e.deltaY*16 : e.deltaMode===2 ? e.deltaY*400 : e.deltaY;
  zoomAt(e.clientX,e.clientY,Math.exp(Math.max(-60,Math.min(60,d))*0.0025));
},{passive:false});
addEventListener('keydown',e=>{
  if(e.target && /INPUT|TEXTAREA|BUTTON/.test(e.target.tagName)) return;
  const step=40;
  if(e.key==='ArrowLeft'){applyDrag(step,0);} else if(e.key==='ArrowRight'){applyDrag(-step,0);}
  else if(e.key==='ArrowUp'){applyDrag(0,step);} else if(e.key==='ArrowDown'){applyDrag(0,-step);}
  else if(e.key==='+'||e.key==='='){camDist/=1.15;} else if(e.key==='-'){camDist*=1.15;} else return;
  autoSpin=false; tween=null; updateCamera(); e.preventDefault();
});

function tapAt(x,y){
  if(state.phase!=='guess') return;
  const ll=hitGlobe(x,y); if(!ll) return;
  state.guess=ll; placePin(guessPin, ll.lat, ll.lon); guessPin.visible=true;
  ui.confirm.disabled=false; ui.hint.textContent=`Pin at ${ll.lat.toFixed(1)}°, ${ll.lon.toFixed(1)}° — tap again to move it.`;
}

// ---------- Game state ----------
const ui={}; ['modeline','score','rounddots','city','country','hint','fact','result','km','pts','confirm','next','sheet','sheetMeta','total','rows','copy','replay','close','toast','tag','mDaily','mPractice','prompt'].forEach(id=>ui[id]=document.getElementById(id));
const guessPin=makePin(0xFF7A59); guessPin.visible=false; markers.add(guessPin);
const truthPin=makePin(0x6EE7A4, 0.012); truthPin.visible=false; markers.add(truthPin);
let arcLine=null;
const state={mode:'daily', seed:0, cities:[], round:0, results:[], phase:'guess', guess:null};

function modeLabel(){ return state.mode==='daily' ? `Daily · ${new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'})}` : `Practice · #${state.seed%10000}`; }

function start(mode){
  state.mode=mode;
  state.seed = mode==='daily' ? seedFromDate(new Date()) : Math.floor(Math.random()*1e9);
  state.cities=pickFive(state.seed); state.round=0; state.results=[]; state.phase='guess'; state.guess=null;
  ui.mDaily.classList.toggle('on',mode==='daily'); ui.mPractice.classList.toggle('on',mode!=='daily');
  ui.modeline.textContent=modeLabel(); ui.sheet.classList.remove('open');
  clearMarks(); ui.score.textContent='0';
  const saved = mode==='daily' && store.get('nightfall:'+dateKey(new Date()));
  if(saved){ state.results=saved; state.round=5; showSheet(true); ui.prompt.hidden=true; setTimeout(recenter,50); return; }
  ui.prompt.hidden=false;
  showRound();
}
function clearMarks(){ guessPin.visible=false; truthPin.visible=false; if(arcLine){markers.remove(arcLine); arcLine=null;} ui.tag.style.display='none'; }
function showRound(){
  const c=state.cities[state.round]; state.phase='guess'; state.guess=null; clearMarks(); canvas.classList.add('pinning');
  if(state.round>0 || camDist<FIT_D-0.01) recenter();
  ui.city.textContent=c[0]; ui.country.textContent=c[1];
  ui.hint.hidden=false; ui.hint.textContent='Spin the globe, then tap where you think it is.';
  ui.fact.hidden=true; ui.result.hidden=true; ui.confirm.hidden=false; ui.confirm.disabled=true; ui.next.hidden=true;
  ui.rounddots.innerHTML=state.cities.map((_,i)=>`<i class="${i<state.round?'done':i===state.round?'cur':''}"></i>`).join('');
}
ui.confirm.addEventListener('click',()=>{
  if(!state.guess) return;
  const c=state.cities[state.round]; const truth={lat:c[2],lon:c[3]};
  const km=haversine(state.guess,truth), pts=pointsFor(km);
  state.results.push({name:c[0],country:c[1],km,pts,guess:state.guess,truth});
  state.phase='reveal'; canvas.classList.remove('pinning');
  placePin(truthPin,truth.lat,truth.lon); truthPin.visible=true;
  arcLine=arcBetween(state.guess,truth,0xF5B63E); markers.add(arcLine);
  ui.km.innerHTML=`${fmtKm(km)}<small>km off</small>`; ui.pts.innerHTML=`+${pts}<small>pts</small>`;
  ui.result.hidden=false; ui.hint.hidden=true; ui.fact.textContent=c[4]; ui.fact.hidden=false;
  ui.confirm.hidden=true; ui.next.hidden=false; ui.next.textContent = state.round===4 ? 'See results' : 'Next city';
  ui.score.textContent=state.results.reduce((s,r)=>s+r.pts,0);
  ui.tag.textContent=c[0]; ui.tag.style.display='block';
  // fly to midpoint
  const mid=latLonToVec3(state.guess.lat,state.guess.lon).add(latLonToVec3(truth.lat,truth.lon));
  const ml = mid.length()<1e-3 ? truth : vec3ToLatLon(mid);
  const d=Math.min(MAX_D, Math.max(1.8, 1.6 + km/4000));
  flyTo(ml.lat, ml.lon, d);
});
ui.next.addEventListener('click',()=>{
  state.round++;
  if(state.round>=5){ if(state.mode==='daily') store.set('nightfall:'+dateKey(new Date()), state.results); showSheet(false); }
  else showRound();
});

function square(km){ return km<250?'🟩':km<1000?'🟨':km<3000?'🟧':'🟥'; }
function squareColor(km){ return km<250?'#6EE7A4':km<1000?'#F5B63E':km<3000?'#F0803C':'#E0525A'; }
function showSheet(fromSave){
  const total=state.results.reduce((s,r)=>s+r.pts,0); ui.score.textContent=total;
  document.getElementById('sheetTitle').textContent = state.mode==='daily' ? "Tonight's five" : 'Practice round';
  ui.sheetMeta.textContent = (state.mode==='daily' ? new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}) : `Set #${state.seed%10000}`) + (fromSave?' · already played today':'');
  ui.total.textContent=total;
  ui.rows.innerHTML=state.results.map(r=>`<tr><td><span class="sq" style="background:${squareColor(r.km)}"></span>${r.name}<div class="c" style="padding-left:20px">${r.country}</div></td><td class="num">${fmtKm(r.km)} km</td><td class="num">${r.pts}</td></tr>`).join('');
  ui.replay.textContent = state.mode==='daily' ? 'Practice round' : 'New practice set';
  ui.sheet.classList.add('open');
}
ui.copy.addEventListener('click',async()=>{
  const total=state.results.reduce((s,r)=>s+r.pts,0);
  const head = state.mode==='daily' ? `Nightfall Globe · ${dateKey(new Date())}` : `Nightfall Globe · practice #${state.seed%10000}`;
  const text=`${head}\n${state.results.map(r=>square(r.km)).join('')} ${total}/5000\n${state.results.map(r=>`${square(r.km)} ${r.name} — ${fmtKm(r.km)} km`).join('\n')}`;
  try{ await navigator.clipboard.writeText(text); toast('Copied to clipboard'); }catch(e){ toast('Copy blocked — select the table instead'); }
});
ui.replay.addEventListener('click',()=>start('practice'));
ui.close.addEventListener('click',()=>{ ui.sheet.classList.remove('open'); ui.prompt.hidden = state.mode==='daily' && state.round>=5; setTimeout(recenter,50); });
ui.mDaily.addEventListener('click',()=>start('daily'));
ui.mPractice.addEventListener('click',()=>start('practice'));
function toast(msg){ ui.toast.textContent=msg; ui.toast.classList.add('show'); setTimeout(()=>ui.toast.classList.remove('show'),1600); }

// ---------- Loop ----------
const ease=t=>t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;
function frame(now){
  if(tween){ const tt=Math.min(1,(now-tween.t0)/tween.dur), k=ease(tt); earth.quaternion.copy(tween.q0).slerp(tween.q1,k); camDist=tween.d0+(tween.d1-tween.d0)*k; updateCamera(); if(tt>=1) tween=null; }
  else if(!dragging && spin.rate>1e-6){ rotateBy(spin.axis, Math.min(0.25, spin.rate*16)); levelNorth(0.5); spin.rate*=0.93; if(spin.rate<2e-5) spin.rate=0; }
  else if(autoSpin && !dragging){ rotateBy(Y_AXIS, 0.0008); }
  // pulse rings
  // markers keep a constant size on screen (7px dot, ring out to ~15px) whatever the zoom
  const s=1+0.12*Math.sin(now/300); const ps=7*radPerPx()/0.014; [guessPin,truthPin].forEach(p=>{ if(p.visible){ p.scale.setScalar(ps); p.children[1].scale.set(s,s,1);} });
  // tag position
  if(truthPin.visible){
    const v=truthPin.getWorldPosition(new THREE.Vector3()); const facing = v.clone().normalize().z>0.15;
    v.project(camera); ui.tag.style.display=facing?'block':'none';
    const cr=canvas.getBoundingClientRect(); ui.tag.style.left=(cr.left+(v.x+1)/2*cr.width)+'px'; ui.tag.style.top=(cr.top+(1-v.y)/2*cr.height)+'px';
  }
  tickLayers(now);
  renderer.render(scene,camera); requestAnimationFrame(frame);
}
requestAnimationFrame(frame);
start('daily');
