"""Build cities.js: every city with population >= 100,000 from GeoNames (cities15000 dump, CC BY 4.0,
https://download.geonames.org/export/dump/), merged with the hand-written facts in data/curated.json.
Usage: build_cities.py <dir containing cities15000.txt, countryInfo.txt, admin1CodesASCII.txt>"""
import json, math, os, sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
D = sys.argv[1]
MIN_POP = 100_000
# PPLX = section of a city (boroughs, wards), PPLH/PPLQ = historical or abandoned, PPLL/PPLS = localities and clusters
KEEP = {"PPL", "PPLA", "PPLA2", "PPLA3", "PPLA4", "PPLA5", "PPLC", "PPLCH", "PPLF", "PPLG"}

countries = {}
for line in open(os.path.join(D, "countryInfo.txt"), encoding="utf-8"):
    if line.startswith("#"): continue
    f = line.rstrip("\n").split("\t")
    countries[f[0]] = f[4]
admin1 = {}
for line in open(os.path.join(D, "admin1CodesASCII.txt"), encoding="utf-8"):
    f = line.rstrip("\n").split("\t")
    admin1[f[0]] = f[1]

rows, small = [], []
for line in open(os.path.join(D, "cities15000.txt"), encoding="utf-8"):
    f = line.rstrip("\n").split("\t")
    pop = int(f[14] or 0)
    if f[7] not in KEEP: continue
    (rows if pop >= MIN_POP else small).append({"name": f[1], "lat": float(f[4]), "lon": float(f[5]), "cc": f[8],
                 "country": countries.get(f[8], f[8]), "region": admin1.get(f[8] + "." + f[10], ""), "pop": pop})

def km(a, b):
    la1, lo1, la2, lo2 = map(math.radians, (a["lat"], a["lon"], b["lat"], b["lon"]))
    s = math.sin((la2 - la1) / 2) ** 2 + math.cos(la1) * math.cos(la2) * math.sin((lo2 - lo1) / 2) ** 2
    return 6371 * 2 * math.asin(math.sqrt(s))

# attach the curated facts: nearest GeoNames city within 40 km keeps the curated name, country and note
curated = json.load(open(os.path.join(ROOT, "data", "curated.json"), encoding="utf-8"))
unmatched = 0
for name, country, lat, lon, note in curated:
    c = {"lat": lat, "lon": lon}
    best = min(rows, key=lambda r: km(r, c))
    if km(best, c) <= 40:
        best.update(name=name, country=country, note=note, curated=True)
    else:  # a curated town under 100k: keep it, taking its population from the smaller GeoNames places if it is there
        unmatched += 1
        near = min(small, key=lambda r: km(r, c))
        pop = near["pop"] if km(near, c) <= 40 else 15_000
        print("under 100k, kept:", name, country, pop)
        rows.append({"name": name, "lat": lat, "lon": lon, "cc": near["cc"], "country": country, "region": "", "pop": pop, "note": note, "curated": True})

def popnote(p):
    if p >= 1_000_000: return f"Home to about {p/1e6:.1f} million people."
    return f"Home to about {round(p, -3):,} people."

# the state/province/oblast goes in the country line for these big countries always, and elsewhere for ambiguous names
ALWAYS_REGION = {"CN", "RU", "BR", "IN", "AU", "ID"}
dupes = {n for n, k in Counter(r["name"] for r in rows).items() if k > 1}
out = []
for r in sorted(rows, key=lambda r: -r["pop"]):
    country = r["country"]
    # municipalities whose region is their own name still show it there ("Beijing, Beijing, China"), except for
    # ambiguous names outside those countries, where it would add nothing
    if r["region"] and (r["cc"] in ALWAYS_REGION or (r["name"] in dupes and r["region"] != r["name"])):
        country = f"{r['region']}, {country}"
    out.append([r["name"], country, round(r["lat"], 3), round(r["lon"], 3), r.get("note") or popnote(r["pop"]), r["pop"]])

with open(os.path.join(ROOT, "cities.js"), "w", encoding="utf-8") as f:
    f.write("// generated by tools/build_cities.py from GeoNames cities15000 (CC BY 4.0): every city with population >= %d\n" % MIN_POP)
    f.write("// [name, country, lat, lon, note, population]\nconst CITIES = [\n")
    f.write(",\n".join(json.dumps(o, ensure_ascii=False) for o in out))
    f.write("\n];\n")
print(f"{len(out)} cities ({len(curated)} curated, {unmatched} curated with no GeoNames match), {len(dupes)} ambiguous names")
