"""Write tiles/manifest.js: the tile lists the page loads, as relative paths."""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
T = os.path.join(ROOT, "tiles")

def load(name):
    p = os.path.join(T, name)
    return json.load(open(p)) if os.path.exists(p) else []

hi = [f"tiles/hi/{i}_{j}.webp" for j in range(4) for i in range(8)]
z7 = [[*m[:4], f"tiles/z7/{m[4]}"] for m in load("z7.json")]
z8 = [[*m[:4], f"tiles/z8/{m[4]}"] for m in load("z8.json")]
out = "// generated by tools/manifest.py\n"
out += 'const TILES = {\n  base: "tiles/base.webp",\n'
out += "  // 8x4 grid of 2048px tiles cut from a 16384x8192 equirectangular composite (NASA, 2012 VIIRS DNB)\n"
out += "  hi: " + json.dumps(hi) + ",\n"
out += "  // ~1.2 km/px patches over every lit region and game city: [lon0, lon1, lat0, lat1, src]\n"
out += "  z7: " + json.dumps(z7, separators=(",", ":")) + ",\n"
out += "  // ~490 m/px tiles (NASA GIBS VIIRS_CityLights_2012, EPSG:4326 level 7) over the same regions\n"
out += "  z8: " + json.dumps(z8, separators=(",", ":")) + "\n};\n"
open(os.path.join(T, "manifest.js"), "w").write(out)
print(f"manifest: {len(hi)} hi, {len(z7)} z7, {len(z8)} z8")
